# Basic Python

## 1. Split this string

In [1]:
s = "Hi there Sam!"

In [2]:
print(s.split())

['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [3]:
planet = "Earth"
diameter = 12742

In [9]:
[print("The diameter of {} is {} kilometers.".format(planet,diameter))]

The diameter of Earth is 12742 kilometers.


[None]

## 3. In this nest dictionary grab the word "hello"

In [10]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [12]:
print(d['k1'][3]["tricky"][3]['target'][3])

hello


# Numpy

In [15]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [17]:
print(np.zeros(10)*5)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [12]:
print(np.ones())

## 5. Create an array of all the even integers from 20 to 35

In [18]:
np.arange(20,35.2)

array([20., 21., 22., 23., 24., 25., 26., 27., 28., 29., 30., 31., 32.,
       33., 34., 35.])

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [19]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [25]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.concatenate((a,b),axis=0))

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [20]:
import pandas as pd


In [21]:
df=pd.DataFrame()

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [36]:
import datetime
test_date=datetime.datetime.strptime("01-01-2023", "%d-%m-%Y")
K=41
date_generated=pd.date_range(test_date,periods=K)


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [26]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [27]:
df=pd.DataFrame(lists,columns=['SI','Name','number'])
print(df)

   SI Name  number
0   1  aaa      22
1   2  bbb      25
2   3  ccc      24
